Data Preprocessing

The goal of this notebook is to clean and transform the raw customer data into a format suitable for machine learning. This includes handling data quality issues, converting data types, encoding categorical variables, and preparing the dataset for model training.

In [32]:
import pandas as pd
import numpy as np

df = pd.read_csv("../data/raw/WA_Fn-UseC_-Telco-Customer-Churn.csv")

df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [33]:
# Lets investigate "TotalCharges" which should be int but is stored as String 
# Lets also look for missing values in it

df["TotalCharges"].dtype

In [34]:
(df["TotalCharges"] == " ").sum()

np.int64(11)

In [35]:
# Lets take a look at who these customers are 

df[df["TotalCharges"] == " "]

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
488,4472-LVYGI,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,...,Yes,Yes,Yes,No,Two year,Yes,Bank transfer (automatic),52.55,,No
753,3115-CZMZD,Male,0,No,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.25,,No
936,5709-LVOEQ,Female,0,Yes,Yes,0,Yes,No,DSL,Yes,...,Yes,No,Yes,Yes,Two year,No,Mailed check,80.85,,No
1082,4367-NUYAO,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.75,,No
1340,1371-DWPAZ,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,...,Yes,Yes,Yes,No,Two year,No,Credit card (automatic),56.05,,No
3331,7644-OMVMY,Male,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,19.85,,No
3826,3213-VVOLG,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.35,,No
4380,2520-SGTTA,Female,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.00,,No
5218,2923-ARZLG,Male,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,One year,Yes,Mailed check,19.70,,No
6670,4075-WKNIU,Female,0,Yes,Yes,0,Yes,Yes,DSL,No,...,Yes,Yes,Yes,No,Two year,No,Mailed check,73.35,,No
6754,2775-SEFEE,Male,0,No,Yes,0,Yes,Yes,DSL,Yes,...,No,Yes,No,No,Two year,Yes,Bank transfer (automatic),61.90,,No

As visible, the tenure for these customers is 0, which means they are new customers and have not been charged yet. We can safely remove these rows from the dataset.

In [36]:
df["TotalCharges"] = pd.to_numeric(
    df["TotalCharges"],
    errors="coerce"
)

In [37]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   str
 1   gender            7043 non-null   str
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   str
 4   Dependents        7043 non-null   str
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   str
 7   MultipleLines     7043 non-null   str
 8   InternetService   7043 non-null   str
 9   OnlineSecurity    7043 non-null   str
 10  OnlineBackup      7043 non-null   str
 11  DeviceProtection  7043 non-null   str
 12  TechSupport       7043 non-null   str
 13  StreamingTV       7043 non-null   str
 14  StreamingMovies   7043 non-null   str
 15  Contract          7043 non-null   str
 16  PaperlessBilling  7043 non-null   str
 17  PaymentMethod     7043 non-null   str
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7043 non-null   str
dtypes: float64(2), int64(2), str(17)
memory usage: 1.1 MB

In [38]:
df.isnull().sum()

customerID           0
gender               0
SeniorCitizen        0
Partner              0
Dependents           0
tenure               0
PhoneService         0
MultipleLines        0
InternetService      0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Contract             0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges       0
TotalCharges        11
Churn                0
dtype: int64

In [39]:
# drop the rows with missing values in TotalCharges
df.dropna(inplace=True)
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [40]:
# lets remove the customerID column as it is not useful for our analysis
df.drop(columns=["customerID"], inplace=True)

In [41]:
# Lets encode the target variable "Churn" to 0 and 1 for No and Yes respectively
df["Churn"] = df["Churn"].map(
    {"No": 0, "Yes": 1}
)

In [42]:
df["Churn"].value_counts()

Churn
0    5163
1    1869
Name: count, dtype: int64

In [43]:
# Separate the features and target variable

X = df.drop("Churn", axis=1)

y = df["Churn"]

In [44]:
categorical_cols = X.select_dtypes(include="object").columns.tolist()

numerical_cols = X.select_dtypes(include=["int64", "float64"]).columns.tolist()

print(categorical_cols)
print(numerical_cols)

['gender', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod']
['SeniorCitizen', 'tenure', 'MonthlyCharges', 'TotalCharges']

/var/folders/hs/5tjjygrd7_xd6q2cfnmr5hlm0000gn/T/ipykernel_40155/2971393759.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = X.select_dtypes(include="object").columns.tolist()

In [45]:
# Lets do train-test-split 

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, 
    y, 
    test_size=0.2, 
    random_state=42,       # Ensures reproducibility
    stratify=y             # preserves the class distribution in both sets
    )

In [46]:
print("Training Shape:", X_train.shape)
print("Testing Shape:", X_test.shape)

Training Shape: (5625, 19)
Testing Shape: (1407, 19)

In [47]:
print(y_train.value_counts(normalize=True))

print()

print(y_test.value_counts(normalize=True))

Churn
0    0.734222
1    0.265778
Name: proportion, dtype: float64

Churn
0    0.734186
1    0.265814
Name: proportion, dtype: float64

In [48]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

In [49]:
numeric_transformer = Pipeline(
    steps=[
        ("scaler", StandardScaler())
    ]
)

In [50]:
categorical_transformer = Pipeline(
    steps=[
        ("encoder", OneHotEncoder(handle_unknown="ignore"))      # encoder safely ignores unseen categories
    ]
)

In [51]:
preprocessor = ColumnTransformer(
    transformers=[
        ("num", numeric_transformer, numerical_cols),
        ("cat", categorical_transformer, categorical_cols)
    ]
)

In [52]:
X_train_processed = preprocessor.fit_transform(X_train)
X_test_processed = preprocessor.transform(X_test) # We only transform the test set, not fit it, to avoid data leakage

In [53]:
print(X_train_processed.shape)
print(X_test_processed.shape)
print(preprocessor.get_feature_names_out())

(5625, 45)
(1407, 45)
['num__SeniorCitizen' 'num__tenure' 'num__MonthlyCharges'
 'num__TotalCharges' 'cat__gender_Female' 'cat__gender_Male'
 'cat__Partner_No' 'cat__Partner_Yes' 'cat__Dependents_No'
 'cat__Dependents_Yes' 'cat__PhoneService_No' 'cat__PhoneService_Yes'
 'cat__MultipleLines_No' 'cat__MultipleLines_No phone service'
 'cat__MultipleLines_Yes' 'cat__InternetService_DSL'
 'cat__InternetService_Fiber optic' 'cat__InternetService_No'
 'cat__OnlineSecurity_No' 'cat__OnlineSecurity_No internet service'
 'cat__OnlineSecurity_Yes' 'cat__OnlineBackup_No'
 'cat__OnlineBackup_No internet service' 'cat__OnlineBackup_Yes'
 'cat__DeviceProtection_No' 'cat__DeviceProtection_No internet service'
 'cat__DeviceProtection_Yes' 'cat__TechSupport_No'
 'cat__TechSupport_No internet service' 'cat__TechSupport_Yes'
 'cat__StreamingTV_No' 'cat__StreamingTV_No internet service'
 'cat__StreamingTV_Yes' 'cat__StreamingMovies_No'
 'cat__StreamingMovies_No internet service' 'cat__StreamingMovies_Yes'
 'cat__Contract_Month-to-month' 'cat__Contract_One year'
 'cat__Contract_Two year' 'cat__PaperlessBilling_No'
 'cat__PaperlessBilling_Yes'
 'cat__PaymentMethod_Bank transfer (automatic)'
 'cat__PaymentMethod_Credit card (automatic)'
 'cat__PaymentMethod_Electronic check' 'cat__PaymentMethod_Mailed check']

In [54]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix,
    classification_report
)

In [55]:
# train logistic regression model

lr = LogisticRegression(random_state=42)
lr.fit(X_train_processed, y_train)
y_pred = lr.predict(X_test_processed)

In [56]:
def evaluate_model(model, X_test, y_test):

    y_pred = model.predict(X_test)

    return {
        "Accuracy": accuracy_score(y_test, y_pred),
        "Precision": precision_score(y_test, y_pred),
        "Recall": recall_score(y_test, y_pred),
        "F1": f1_score(y_test, y_pred),
        "ROC-AUC": roc_auc_score(
            y_test,
            model.predict_proba(X_test)[:,1]
        )
    }

In [57]:
# evaluate the logistic regression model

evaluate_model(lr, X_test_processed, y_test)

{'Accuracy': 0.8038379530916845,
 'Precision': 0.6484848484848484,
 'Recall': 0.5721925133689839,
 'F1': 0.6079545454545454,
 'ROC-AUC': 0.8359290473207676}

In [58]:
# train decision tree model

dt = DecisionTreeClassifier(
    random_state=42
)

dt.fit(X_train_processed, y_train)

evaluate_model(
    dt,
    X_test_processed,
    y_test
)

{'Accuracy': 0.7356076759061834,
 'Precision': 0.5026315789473684,
 'Recall': 0.5106951871657754,
 'F1': 0.506631299734748,
 'ROC-AUC': 0.6633927970554586}

In [59]:
# train random forest classifier

rf = RandomForestClassifier(
    random_state=42
)

rf.fit(
    X_train_processed,
    y_train
)

evaluate_model(
    rf,
    X_test_processed,
    y_test
)

{'Accuracy': 0.783226723525231,
 'Precision': 0.6193771626297578,
 'Recall': 0.4786096256684492,
 'F1': 0.5399698340874811,
 'ROC-AUC': 0.8133273110353004}

In [60]:
# train xgBoost

from xgboost import XGBClassifier

xgb = XGBClassifier(
    random_state=42,
    eval_metric="logloss"
)

xgb.fit(
    X_train_processed,
    y_train
)

evaluate_model(
    xgb,
    X_test_processed,
    y_test
)

{'Accuracy': 0.7690120824449183,
 'Precision': 0.5710144927536231,
 'Recall': 0.5267379679144385,
 'F1': 0.5479833101529903,
 'ROC-AUC': 0.8119127612322761}

In [61]:
# Lets compare the performance of all the models we have trained so far

results = pd.DataFrame({
    "Logistic Regression": evaluate_model(lr, X_test_processed, y_test),
    "Decision Tree": evaluate_model(dt, X_test_processed, y_test),
    "Random Forest": evaluate_model(rf, X_test_processed, y_test),
    "XGBoost": evaluate_model(xgb, X_test_processed, y_test)
}).T

results

                     Accuracy  Precision    Recall        F1   ROC-AUC
Logistic Regression  0.803838   0.648485  0.572193  0.607955  0.835929
Decision Tree        0.735608   0.502632  0.510695  0.506631  0.663393
Random Forest        0.783227   0.619377  0.478610  0.539970  0.813327
XGBoost              0.769012   0.571014  0.526738  0.547983  0.811913

Observations :
- Logistic Regression is the best model across almost every metric
- Decision Tree is clearly overfitting. Accuracy, ROC-AUC, F1 dropped.
- Random Forest improved over Decision Tree. Ensembling reduced overfitting
- XBBoost is not performing well, it needs hyperparameter tuning.

In [ ]:
# Now lets tune XGBoost, Random Forest uisng RandomizedSearchCV